import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
// para importar otra tipografia se importa aqui
//Fira_Sans_Condensed
import { IBM_Plex_Sans, Inter, Fira_Sans_Condensed } from 'next/font/google'
import { preload } from 'react-dom'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Font = IBM_Plex_Sans({
  display: 'swap',
  weight: ['400', '500', '700'],
  adjustFontFallback: true,
  fallback: ['Inter'],
  preload: true,
  style: 'normal',
  subsets: ['latin-ext'],
})
// ejemplo de importar otra tipografia
const Font2 = Fira_Sans_Condensed({
  weight: ['400', '500', '700'],
  subsets: ['latin-ext'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={Font.className}>
      <body>
        <Navbar />

        {children}
      </body>
    </html>
  )
}
